### ISSUE TITLE
Se debe poder recuperar una lista ordenada alfabéticamente de las claves almacenadas

### ISSUE THREAD

**Issue by evolentini** [nhasbun/lse_fiuba_testing_iot_tdd#2]
Este requerimiento no está implementado. La idea es que un método de la lista retorne un arreglo con todas las claves almacenadas en la lista ordenadas alfabéticamente.

**Comment by nhasbun** [comment]
Duplicate of #1 

Existió una confusión con respecto a lo que entendí por orden. Se va a corregir junto con el issue #1 en un mismo commit.
