### ISSUE TITLE
No se deben implementar funcionalidades que no están en los requerimientos

### ISSUE THREAD

**Issue by evolentini** [nhasbun/lse_fiuba_testing_iot_tdd#3]
No se pide una función que retorne el indice de una clave porque la lista como tal no tiene orden. Acceder al indice dentro de la colección crea una dependencia con la implementación que no se desea en las especificaciones propuestas.

https://github.com/nhasbun/lse_fiuba_testing_iot_tdd/blob/6f308fedd39cfb0a128deb227850e39cfefcf7cb/test/test_lista.js#L55-L59

**Comment by nhasbun** [comment]
Problema asociado a #1 #2 

Existió una confusión con el requerimiento de cómo se espera acceder a las llaves por parte de la librería. Se va a corregir siguiendo el issue #1.
